#!/bin/sh
# Derived from http://offbytwo.com/2008/05/09/show-ip-address-of-vm-as-console-pre-login-message.html
if [ "$METHOD" = loopback ]; then
    exit 0
fi

# Only run from ifup.
if [ "$MODE" != start ]; then
    exit 0
fi

cp /etc/issue-base /etc/issue
ip=$(ip -f inet -o addr show eth0 | awk '{ print $4 }' | cut -d/ -f 1)
sed -i -e 's/__IP__/$ip/g' /etc/issue


